### PR TITLE
Http Cache Fix (Issue #159)

### PR DESCRIPTION
**Pull request by david-bergman**
Fix in order to avoid fatal concurrency error trying to write to a map with the same key concurrently. 

fatal error: concurrent map writes

### CODE REVIEW

**Comment by kjk** [comment]
This is likely not enough i.e. both reads and writes to all data in genericCache needs to be protected with the mutex.

**Review by ayende — COMMENTED** [review]
I don't know if this is enough. 
Don't we need to also protect the map on the read side as well?

I wonder if we aren't better off using `sync.Map` instead. The key use cases for that seems to be mostly write only / disjoint writes and many reads.

I think that this might be a better option, thoughts?

**Comment by david-bergman** [comment]
you referring to the invalidateAll func? I dont know the repo well enough to answer that.

**Comment by david-bergman** [comment]
I tried setting it to sync.map, I dont think it can be set like that .. apologies Golang is very new to me. 

image

**Comment by ayende** [comment]
Fixed here: https://github.com/ravendb/ravendb-go-client/commit/5ff65ecb135471d6b7888f0e5867cfde10fecc63

**Pull request closed without merging**
